version: 2.1

orbs: 
  python: circleci/python@2.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          name: Run Test
          command: | 
            pip install pytest
            pip install requests
            pytest --junitxml=test-results/junit.xml testGit.py
      - store_test_results:
          path: test-results
workflows:
  testing:
    jobs:
      - build-and-test
